Feature/register
bakidkbyk/fodamy-umitbaki pull request #13
Opened 2023-01-25 06:01 UTC by bakidkbyk

2023-01-25 06:24 UTC, mrtcelebi commented on DataProvider/DataProvider/Model/BaseResponse.swift
> +
içi boş silinmeli

2023-01-25 06:24 UTC, mrtcelebi commented on DataProvider/DataProvider/Request/Auth/RegisterRequest.swift
> +    public var path: String = "auth/register"
let olmalı

2023-01-25 06:24 UTC, mrtcelebi commented on DataProvider/DataProvider/Request/Auth/RegisterRequest.swift
> +    public var method: RequestMethod = .post
let olmalı

2023-01-25 06:24 UTC, mrtcelebi commented on UIComponents/UIComponents/Resources/Strings/Localizable.strings
> +"checkInformations" = "lütfen bilgilerinizi kontrol ediniz.";
her ekran için yazılar aynı bile olsa farklı keyler ile tutulmalı, genel stringler kullanılmamalı

2023-01-25 06:24 UTC, mrtcelebi commented on UIComponents/UIComponents/Resources/Strings/Localizable.strings
> +// MARK: - Register View Controller
her marktan önce boşluk atılmalı

2023-01-25 06:24 UTC, mrtcelebi commented on UIComponents/UIComponents/Resources/Strings/Localizable.strings
> +"title" = "Üye Ol";
"Register.title" gibi en başta ekran ismi yer almalı
"Register.signUpButtonText" = "sadsdfdaf"

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Login/LoginViewModel.swift
> +import Foundation
silinmeli

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterRoute.swift
> +    func pushRegister() {
route ismi PlaceOnWindowTransition transitiona göre düzenlenmeli placeOnWindowRegister gibi

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +import MobilliumBuilders
global import olduğundan silinmeli

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +import UIKit
global import olduğundan silinmeli

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Login/LoginViewController.swift
> +import UIKit
global import olduğundan silinmeli

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        bottomStackView.leadingToSuperview(relation: .equalOrGreater).constant = 20
burada sabit değil mi sağdan ve soldan margin, relation verilmesine ihtiyaç var mı?

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        titleLabel.centerX(to: contentStackView)
stackView içinde constraint verilmez, label textAlighmnet verebilirsin

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        contentStackView.setCustomSpacing(15, after: usernameTextField)
textFieldleri ayrı bir stack içine alıp customSpacing vermemen daha temiz olur

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        signUpButton.addTarget(self, action: #selector(signUpButtonTapped), for: .touchUpInside)
configureContent içinde yazılmalı

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        setLocalize()
viewDidLoad içinde çağırılmalı

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +                self.router.presentLogin()
login present yerine push mantığı ile yapılması daha iyi olur

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +                self.showWarningToast?("\(error.localizedDescription) \(L10n.checkInformations)")
apiden gelen hata yeterli L10n.checkInformations gibi bir key eklemeye gerek yok

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +    func sendRegisterRequest(username: String, email: String, password: String) {
her extensiondan sonra bir boşluk atılmalı

2023-01-25 06:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +
boşluk silnmeli

2023-01-25 10:38 UTC, bakidkbyk commented on DataProvider/DataProvider/Model/BaseResponse.swift
> +
düzeltildi.

2023-01-25 10:39 UTC, bakidkbyk commented on DataProvider/DataProvider/Request/Auth/RegisterRequest.swift
> +    public var path: String = "auth/register"
düzeltildi

2023-01-25 10:40 UTC, bakidkbyk commented on DataProvider/DataProvider/Request/Auth/RegisterRequest.swift
> +    public var method: RequestMethod = .post
düzeltildi

2023-01-25 10:44 UTC, bakidkbyk commented on UIComponents/UIComponents/Resources/Strings/Localizable.strings
> +// MARK: - Register View Controller
düzeltildi

2023-01-25 18:15 UTC, bakidkbyk commented on UIComponents/UIComponents/Resources/Strings/Localizable.strings
> +"title" = "Üye Ol";
düzeltildi

2023-01-25 18:15 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Login/LoginViewModel.swift
> +import Foundation
düzeltildi

2023-01-25 18:20 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterRoute.swift
> +    func pushRegister() {
düzeltildi.

2023-01-25 18:21 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +import MobilliumBuilders
düzeltildi

2023-01-25 18:21 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +import UIKit
düzeltildi

2023-01-25 18:21 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Login/LoginViewController.swift
> +import UIKit
düzeltildi

2023-01-25 18:23 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        bottomStackView.leadingToSuperview(relation: .equalOrGreater).constant = 20
düzeltildi

2023-01-25 18:24 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        titleLabel.centerX(to: contentStackView)
label textalignment vermiştim onu silmeyi unutmuşum düzeltildi

2023-01-25 18:31 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        contentStackView.setCustomSpacing(15, after: usernameTextField)
düzeltildi

2023-01-25 18:39 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        signUpButton.addTarget(self, action: #selector(signUpButtonTapped), for: .touchUpInside)
düzeltildi

2023-01-25 18:39 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        setLocalize()
düzeltildi

2023-01-25 18:40 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +                self.router.presentLogin()
login ekranını sildim oraya print döndürdüm login ekranında düzelticem orayı

2023-01-25 18:41 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +                self.showWarningToast?("\(error.localizedDescription) \(L10n.checkInformations)")
düzeltildi

2023-01-25 18:42 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +    func sendRegisterRequest(username: String, email: String, password: String) {
düzeltildi

2023-01-25 18:42 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +
düzeltildi

2023-01-25 20:24 UTC, mrtcelebi requested changes

2023-01-25 20:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        bottomStackView.bottomToSuperview(usingSafeArea: true)
leading ve trailing verilmesi gerekiyor

2023-01-25 20:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        bottomStackView.addArrangedSubview(bottomLabel)
bottomLabel yerine anlamli isimlendirilme verilmeli

2023-01-25 20:24 UTC, mrtcelebi commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +        print("bottom buttona tıklandı.")
print yerine TODO yazilmali

2023-01-26 06:20 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        bottomStackView.addArrangedSubview(bottomLabel)
düzeltildi

2023-01-26 06:22 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewModel.swift
> +        print("bottom buttona tıklandı.")
düzeltildi

2023-01-26 06:29 UTC, bakidkbyk commented on fodamy-baki/Scenes/Auth/Register/RegisterViewController.swift
> +        bottomStackView.bottomToSuperview(usingSafeArea: true)
düzeltildi

2023-01-26 06:31 UTC, merged